- hosts: all

  tasks:
  - name: stop current running container
    command: docker stop ansible-project
    ignore_errors: yes

  - name: remove stopped cotainer
    command: docker rm ansible-project
    ignore_errors: yes

  - name: remove current docker image
    command: docker rmi daeunxx/ansible
    ignore_errors: yes

  - name: pull the newest docker image from Docker hub
    command: docker pull daeunxx/ansible

  - name: create a container using cicd-project-ansible image
    command: docker run -d --name ansible-project -p 8080:8080 daeunxx/ansible
