- name: Create pods using deployment 
  hosts: kubernetes 
 
  tasks:
  - name: delete the previous deployment
    command: /usr/local/bin/kubectl delete deployment.app/cicd-deployment
    ignore_errors: yes

  - name: create a deployment
    command: /usr/local/bin/kubectl apply -f /Users/daeun/IdeaProjects/jenkins/yml/k8s-cicd-devops-deployment.yml
